package api

// Event defines the event shape generated by gomobile for Kotlin and Swift.
// Core does not use this type internally.
type Event struct {
	// Id is the event identifier.
	Id string
	// Title is the event title.
	Title string
	// Location is the event location.
	Location string
	// Description is the event description.
	Description string
	// From is the RFC 3339 event start time, for example "2009-11-10T23:00:00Z",
	// matching time.Time's default JSON encoding.
	From string
	// To is the RFC 3339 event end time, for example "2009-11-10T23:00:00Z",
	// matching time.Time's default JSON encoding.
	To string
	// Calendar is the name of the containing calendar.
	Calendar string
	// TagId is the associated tag identifier.
	TagId string
	// ParentId is the identifier of the parent repeating event.
	ParentId string
	// Repeat is a DTSTART, RRULE, and EXDATE definition in RFC 5545 format.
	Repeat string
}

// Calendar defines the calendar shape generated by gomobile for Kotlin and Swift.
// Core does not use this type internally.
type Calendar struct {
	// Name is the calendar name.
	Name string
	// Tags contains the calendar's tags.
	Tags []Tag
	// RemoteUrl is the configured remote URL.
	RemoteUrl string
	// Encrypted reports whether the calendar is encrypted.
	Encrypted bool
	// Readonly reports whether the calendar is read-only.
	Readonly bool
}

// Tag defines the tag shape generated by gomobile for Kotlin and Swift.
// Core does not use this type internally.
type Tag struct {
	// Id is the tag identifier.
	Id string
	// Name is the tag name.
	Name string
	// Color is the tag color.
	Color string
}
